const axios = require("axios");
const cheerio = require("cheerio");

module.exports = async (req, res) => {
  try {
      const id = req.query.id || "122711961"; // Pode passar ID por query ?id=XXXX

          const url = `https://corehalla.com/stats/player/${id}`;

              const { data } = await axios.get(url, {
                    headers: {
                            "User-Agent": "Mozilla/5.0 (Linux; Android 10; SM-G975F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36",
                                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
                                            "Accept-Language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
                                                    "Accept-Encoding": "gzip, deflate, br",
                                                            "Connection": "keep-alive",
                                                                    "Upgrade-Insecure-Requests": "1",
                                                                            "Referer": "https://corehalla.com/",
                                                                                    "Sec-Fetch-Dest": "document",
                                                                                            "Sec-Fetch-Mode": "navigate",
                                                                                                    "Sec-Fetch-Site": "same-origin",
                                                                                                            "Sec-Fetch-User": "?1"
                                                                                                                  }
                                                                                                                      });

                                                                                                                          const $ = cheerio.load(data);

                                                                                                                              const result = {};

                                                                                                                                  // PLAYER INFO
                                                                                                                                      result.player = {
                                                                                                                                            name: $("h1.font-bold").clone().children().remove().end().text().trim() || "Unknown",
                                                                                                                                                  id: $("span.text-xs").text().replace("#", "").trim() || id,
                                                                                                                                                        flag: "https://corehalla.com" + ($("h1 img").attr("src") || "")
                                                                                                                                                            };

                                                                                                                                                                // RANKED INFO (adaptado para pegar mais campos)
                                                                                                                                                                    result.ranked = {
                                                                                                                                                                          rating: "N/A",
                                                                                                                                                                                peak: "N/A",
                                                                                                                                                                                      tier: "N/A",
                                                                                                                                                                                            region: "N/A",
                                                                                                                                                                                                  wins: "N/A",
                                                                                                                                                                                                        games: "N/A",
                                                                                                                                                                                                              winrate: "N/A"
                                                                                                                                                                                                                  };

                                                                                                                                                                                                                      // Procura textos na página
                                                                                                                                                                                                                          $("div, span, p").each((i, el) => {
                                                                                                                                                                                                                                const text = $(el).text().trim().toLowerCase();

                                                                                                                                                                                                                                      if (text.includes("rating")) {
                                                                                                                                                                                                                                              const value = $(el).next().text().trim() || $(el).text().split("rating")[1]?.trim();
                                                                                                                                                                                                                                                      if (value) result.ranked.rating = value;
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                  if (text.includes("peak")) {
                                                                                                                                                                                                                                                                          const value = $(el).next().text().trim() || $(el).text().split("peak")[1]?.trim();
                                                                                                                                                                                                                                                                                  if (value) result.ranked.peak = value;
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                              if (text.includes("tier")) {
                                                                                                                                                                                                                                                                                                      const value = $(el).next().text().trim() || $(el).text().split("tier")[1]?.trim();
                                                                                                                                                                                                                                                                                                              if (value) result.ranked.tier = value;
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                          if (text.includes("region")) {
                                                                                                                                                                                                                                                                                                                                  const value = $(el).next().text().trim() || $(el).text().split("region")[1]?.trim();
                                                                                                                                                                                                                                                                                                                                          if (value) result.ranked.region = value;
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                      if (text.includes("wins")) {
                                                                                                                                                                                                                                                                                                                                                              const value = $(el).next().text().trim() || $(el).text().split("wins")[1]?.trim();
                                                                                                                                                                                                                                                                                                                                                                      if (value) result.ranked.wins = value;
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                  if (text.includes("games")) {
                                                                                                                                                                                                                                                                                                                                                                                          const value = $(el).next().text().trim() || $(el).text().split("games")[1]?.trim();
                                                                                                                                                                                                                                                                                                                                                                                                  if (value) result.ranked.games = value;
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                              if (text.includes("winrate")) {
                                                                                                                                                                                                                                                                                                                                                                                                                      const value = $(el).next().text().trim() || $(el).text().split("winrate")[1]?.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                              if (value) result.ranked.winrate = value;
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                            // COMBAT INFO (KOs, falls, etc.)
                                                                                                                                                                                                                                                                                                                                                                                                                                                result.combat = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      kos: "N/A",
                                                                                                                                                                                                                                                                                                                                                                                                                                                            falls: "N/A",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  suicides: "N/A",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        teamKos: "N/A",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              damageDealt: "N/A",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    damageTaken: "N/A"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $("div.stat-value").each((i, el) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const text = $(el).text().trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (text.includes("KOs")) result.combat.kos = text.replace("KOs", "").trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (text.includes("Falls")) result.combat.falls = text.replace("Falls", "").trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (text.includes("Suicides")) result.combat.suicides = text.replace("Suicides", "").trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (text.includes("Team KOs")) result.combat.teamKos = text.replace("Team KOs", "").trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (text.includes("Damage dealt")) result.combat.damageDealt = text.replace("Damage dealt", "").trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (text.includes("Damage taken")) result.combat.damageTaken = text.replace("Damage taken", "").trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.status(200).json(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error("Erro no scraper:", err.message);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (err.response) console.error("Status:", err.response.status);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.status(500).json({ error: "Erro ao puxar dados do Corehalla: " + err.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };